"""Shared plumbing for the report scripts (`make report`).

Every figure and table under ``reports/figures/`` is generated by a script in
this package from real data — the raw CSVs, the live Postgres tables
(predictions/labels/monitoring) and models served by the stack — never by
hand. Stack endpoints default to the host-published ports (Postgres 5433,
MLflow 5000) and can be overridden through the same environment variables
the rest of the project uses.
"""

from __future__ import annotations

import os
from pathlib import Path

os.environ.setdefault("MLFLOW_DISABLE_AGENT_HINT", "1")  # keep script output clean

import matplotlib

matplotlib.use("Agg")  # headless: scripts run from make, never a display

import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

FIGURES_DIR = Path("reports/figures")

# styling: small, sober, print-friendly
plt.rcParams.update(
    {
        "figure.dpi": 150,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "font.size": 9,
    }
)


def load_env(path: Path = Path(".env")) -> None:
    """Import KEY=VALUE lines from .env without overriding real environment.

    Report scripts run on the host against the Docker stack: model artifacts
    live in MinIO, so boto3 needs the same credentials compose uses.
    """
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


def database_url() -> str:
    load_env()
    return os.environ.get(
        "DATABASE_URL", "postgresql://fraudops:fraudops-local@localhost:5433/fraudops"
    )


def tracking_uri() -> str:
    return os.environ.get("MLFLOW_TRACKING_URI", "http://localhost:5000")


def data_dir() -> Path:
    return Path(os.environ.get("FRAUDOPS_DATA_DIR", "data/raw"))


def connect():
    import psycopg

    return psycopg.connect(database_url())


def load_bundle(version: int | None = None):
    """A registered model by explicit version, or the current champion.

    Returns the unwrapped FraudOpsModel (model + pipeline + threshold).
    """
    import mlflow

    from fraudops.registry import client as rc
    from fraudops.registry.wrapper import FraudOpsModel

    load_env()
    mlflow.set_tracking_uri(tracking_uri())
    if version is None:
        version = rc.get_version_by_alias(rc.configure(tracking_uri()), rc.CHAMPION)
        if version is None:
            raise RuntimeError("no champion registered — run bootstrap first")
    pyfunc = mlflow.pyfunc.load_model(f"models:/{rc.model_name()}/{version}")
    return FraudOpsModel.unwrap(pyfunc), int(version)


def model_metrics(version: int) -> dict[str, float]:
    """Logged metrics of a registered version's source run (MLflow is the
    record: reference lines in figures come from here, never from literals)."""
    import mlflow

    from fraudops.registry import client as rc

    load_env()
    mlflow.set_tracking_uri(tracking_uri())
    cli = mlflow.tracking.MlflowClient(tracking_uri=tracking_uri())
    run_id = cli.get_model_version(rc.model_name(), str(version)).run_id
    return dict(cli.get_run(run_id).data.metrics)


def served_labelled_frame(model_version: int) -> pd.DataFrame:
    """The frozen model's served predictions joined to released labels.

    This is the deployment record: scores and decisions exactly as they left
    the scorer, with the truth that arrived 7 simulated days later. Reports
    about the replay period judge the model on this, never on a re-score.
    """
    with connect() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT p.sim_ts, l.is_fraud, l.amount, p.fraud_probability, p.decision
            FROM labels l
            JOIN predictions p ON p.transaction_id = l.transaction_id
            WHERE p.model_version = %s
            ORDER BY p.sim_ts
            """,
            (model_version,),
        )
        rows = cur.fetchall()
    if not rows:
        raise RuntimeError(f"no stored predictions for model version {model_version}")
    return pd.DataFrame(
        rows,
        columns=["sim_ts", "is_fraud", "amount", "score", "decision"],
    )


def save_table(name: str, frame: pd.DataFrame) -> Path:
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    path = FIGURES_DIR / name
    frame.to_csv(path, index=False)
    print(f"wrote {path} ({len(frame)} rows)")
    return path


def save_figure(fig, name: str) -> Path:
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    path = FIGURES_DIR / name
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {path}")
    return path
